from langchain_core.pydantic_v1 import BaseModel, Field
from typing import List
    
class Tables(BaseModel):
    table_name: str = Field(..., title="Name of the filtered table")
    reason: str = Field(..., title="Reason for selecting the filtered table")

class LLM_Table_Filter(BaseModel):
    tables: List[Tables] = Field(..., title="List of tables filtered by LLM to answer the user query") 

class PydanticSqlQuery(BaseModel):
    sql_query: str = Field(..., title="SQL query generated by the LLM to answer the user query")
    reason: str = Field(..., title="Provide step-by-step reasoning for generating the SQL query")